name: Mirror Bot Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Pyrogram
        run: |
          pip install pyrogram tgcrypto

      - name: Start the Script
        run: python main.py
